#+Title: Test case
#+Date: 10 Jan 2017
#+Author: SravanthiB

* Environment

  +  OS: Windows 7, Linux
  +  Browsers: Firefox,Chrome
  +  Bandwidth : 100Mbps
  +  Hardware Configuration:8GBRAM,
  +  Processor:i5

* Objective

   + To be able to simulate the "Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity: Determination of Unknown Concentration of an Analyte" experiment
     
* Pre conditions

  +  Refer to first test case [[https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith/blob/master/test-cases/integration_test-cases/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte/Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte_01_Usability_smk.org][Relationship-between-the-Concentration-of-a-Fluorophore-and-its-Fluorescence-Intensity-Determination-of-Unknown-Concentration-of-an-Analyte_01_Usability_smk.org]]

* Post conditions

  +  Nil
     
* Test Steps

  +  Click on the "Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity: Determination of Unknown Concentration of an Analyte" link.
  +  Check if there are any distortions, spelling mistakes and junk
     characters in the Simulation page.

* Expected result

  + The home page of "Relationship between the Concentration of a Fluorophore and its Fluorescence Intensity: Determination of Unknown Concentration of an Analyte" experiment should be displayed on the screen.
  + The Home page should be present with no distortions, spelling mistakes and Junk characters.

* Review/comments
